//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Student_Exam_Grade_Management_System
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbStudentsAndExamsEntities : DbContext
    {
        public DbStudentsAndExamsEntities()
            : base("name=DbStudentsAndExamsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLEXAM> TBLEXAM { get; set; }
        public virtual DbSet<TBLSTUDENTS> TBLSTUDENTS { get; set; }
        public virtual DbSet<TBLSUBJECTS> TBLSUBJECTS { get; set; }
    }
}
