//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Student_Exam_Grade_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLEXAM
    {
        public int EXGRID { get; set; }
        public Nullable<int> STD { get; set; }
        public Nullable<int> SUB { get; set; }
        public Nullable<short> EXAM1 { get; set; }
        public Nullable<short> EXAM2 { get; set; }
        public Nullable<short> EXAM3 { get; set; }
        public Nullable<decimal> AVRG { get; set; }
        public Nullable<bool> STAT { get; set; }
    
        public virtual TBLSTUDENTS TBLSTUDENTS { get; set; }
        public virtual TBLSUBJECTS TBLSUBJECTS { get; set; }
    }
}
