//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Student_Exam_Grade_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSTUDENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLSTUDENTS()
        {
            this.TBLEXAM = new HashSet<TBLEXAM>();
        }
    
        public int STUDENTNUMBER { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public string STUDENT_PHOTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLEXAM> TBLEXAM { get; set; }
    }
}
